# Generated by Django 2.2.1 on 2019-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureaccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='accessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='element',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
